### ISSUE TITLE
An error occured in reviewer: 'NoneType' object has no attribute 'mapToGlobal'

### ISSUE THREAD

**Issue by nurkittel** [Unlucky-Life/ankimon#21]
Every time my Pokemon defeats another this message 'An error occured in reviewer: 'NoneType' object has no attribute 'mapToGlobal'' as a popup appears after I close the 'Your pokemon is now lvl ...' popup. 

Strange that the first few level worked without that issue. I have the Ankimon Window not open and I can not choose between defeat or catch. Only the popups appear. After that I can open the Ankimon window and choose defeat/catch. If I choose defeat the level up popup appears again but still no level up. If I continue doing reviews no new pokemon appears and I have to restart.

My pokemon does not get that level up after the restart.

Thanks again.

**Comment by Unlucky-Life** [comment]
Could give more infos ? Like what level is your Pokemon now ? could you check how much xp your mainpokemon has ? Does this happen with all pokemon or only with a specific one?

**Comment by nurkittel** [comment]
Lvl 11 with 208exp. I will check if it happen with other as well give me a few minutes.

**Comment by nurkittel** [comment]
No, other Pokemon works fine. But during the last defeat I could not choose between defeat/catch and the popup level up appeared and the enemy pokemon was defeated. I don't know if that is intended. Did not have ankimon windows open.

**Comment by Unlucky-Life** [comment]
So without a ankimon window you cant catch any pokemon but only defeat them - it was thought to me „grind mode“ where you can simply concentrate on leveling your pokemon and wont be annoyed by the ankimon window changing and habent to decideAm 14.03.2024 um 20:07 schrieb nurkittel ***@***.***>:﻿
No, other Pokemon works fine. But during the last defeat I could not choose between defeat/catch and the popup level up appeared and the enemy pokemon was defeated. I don't know if that is intended. Did not have ankimon windows open.

**Comment by Unlucky-Life** [comment]
could you send me the trade code of your charmander ?

**Comment by nurkittel** [comment]
Can I send you the files? 

[mainpokemon.json](https://github.com/Unlucky-Life/ankimon/files/14613260/mainpokemon.json)
[mypokemon.json](https://github.com/Unlucky-Life/ankimon/files/14613262/mypokemon.json)

**Comment by Unlucky-Life** [comment]
ok  just tried it out and i didnt have the leveling issue => Maybe it was due to a generation of new pokemon (which was quite an often error at the moment) But with the new creation logic of new pokemon it should be fixed (Hopefully)!

**Comment by Unlucky-Life** [comment]
[mypokemon.json](https://github.com/Unlucky-Life/ankimon/files/14613461/mypokemon.json)
[mainpokemon.json](https://github.com/Unlucky-Life/ankimon/files/14613465/mainpokemon.json)
=> There you go with a level up 👍  :) => Charmander has dragonbreath now ;)

**Comment by nurkittel** [comment]
Thanks. Yea the generation of new pokemon is sometimes off. I only selected in config to include gen1 and gen2. But sometimes after a few fights it shows a new gen 3,4,5... pokemon. That's the moment I know something is off and I have to restart because I know it won't give exp if that happens.

**Comment by Unlucky-Life** [comment]
[mainpokemon.json](https://github.com/Unlucky-Life/ankimon/files/14613514/mainpokemon.json)
[mypokemon.json](https://github.com/Unlucky-Life/ankimon/files/14613507/mypokemon.json)

=> There you go with a level up 👍 :) => Charmander has dragonbreath now ;)

I also corrected the move set from ponyta and growlithe

**Comment by nurkittel** [comment]
An error occured in reviewer: 'NoneType' object has no attribute 'mapToGlobal' I am getting the error again every time my pokemon gets a new level. Popup directly after the 'your pokemon reached level...' New install. First level wer fine now it's lvl 9 and every level it appears. And in Pokemon collection it still shows level 9.

**Comment by Unlucky-Life** [comment]
Can you imagine something sopecific that could create this bug ?
Does this happen in reviewer or with the ankimon window ?

**Comment by Unlucky-Life** [comment]
Ok i may have found the issue now - its somehow the message boxes in anki which are the issue

**Comment by CHeadn** [comment]
Also having this same issue with my totadile but no others

**Comment by liu1234567891011** [comment]
having same issue with my charmander

**Comment by liu1234567891011** [comment]
stuck at level 5

**Comment by Unlucky-Life** [comment]
ok might have a fix now. Please redownload this file: https://github.com/Unlucky-Life/ankimon/blob/b66509a8004db069cfce4ef826ca7e031ee265d7/src/Ankimon/__init__.py

And overwrite the __init__.py file in the ankimon addon folder.
I hope this should solve the issue.

**Comment by Unlucky-Life** [comment]
i tried to recreate the bug - with and without ankimon window - but wasnt able to. Seems like this is a mac issue which appears due to mac not able to check the windows coordinates. The error was due to the message window not be able to find the proper coordinates. => Let me know if this resolved the issue !

**Comment by Unlucky-Life** [comment]
@nurkittel

**Comment by nurkittel** [comment]
Fixed! Thanks! I learned a new attack for the first time as well. The 'new attack learned' window might have been the reason the problem appeared and didn't appear during the first level.

**Comment by Unlucky-Life** [comment]
Yea maybe - but apparently something screwed around with Anki not being able to find the coordinates of the active anki window right now
=> so it didnt know where to place the Reviewer Message and therefore  saying "NoneType" => basically saying: There is no window i can refer the coordinates to.

**Comment by liu1234567891011** [comment]
works noow thanks
