### ISSUE TITLE
Error while doing cards 

### ISSUE THREAD

**Issue by CaptainDead** [Unlucky-Life/ankimon#75]
I get an error while solving my cards, like this - 
![Screenshot 2024-04-16 225614](https://github.com/Unlucky-Life/ankimon/assets/139457914/edc9ced7-7620-47f6-ae79-a44922f020c8)
Zoomed - 
![image](https://github.com/Unlucky-Life/ankimon/assets/139457914/b545d90b-e263-465f-af1d-0653082f845f)

Recently there is never any popup for the first card, no damage nothing.. and it might persist for long period and sometimes there is no damage from solving cards for a while and then there is a super big damage all of a sudden - 
![Screenshot 2024-04-17 010027](https://github.com/Unlucky-Life/ankimon/assets/139457914/e746ab10-36cb-4290-bffe-70081f1a1e72)
Also my XP bar doesn't get updated after defeating a pokemon (I have to go to deck and come back again to see the xp bar updated) and sometimes I don't get any XP from defeating one pokemones.

Here's a video showing all that - 
https://pixeldrain.com/u/AU5WjGWh

**Comment by CaptainDead** [comment]
Oh wait, one thing I just realised is that maybe not getting damage each time is not a issue but rahter its because I changed ["cards_per_round":] to '2' from '1;, I had it at 1 previously thus I was getting damage each card, so ig ignore the no damage things but the error is still an issue

**Comment by Unlucky-Life** [comment]
@CaptainDead try changing this line in your __init__.py file: `reviewed_cards_count = -1` => to `reviewed_cards_count = 0`

that was my work around i had before another person came up with the fix.
Try changing that line and i think that should fix the issue :)

**Comment by Unlucky-Life** [comment]
@CaptainDead the xp bar is propapbly just updating with a lag - but we found  a fix for that too - ill add that for the next update

**Comment by CaptainDead** [comment]
It did made things better, now I give damage/attacks each time and feels smoother but now the only problem is, I still get the above error... and it doesn't come that often, its rare but if I click on good or hard buttons quickly than that error comes very often, especially if I click on the same review button many times. but if I take my time and solve cards normally than the error doesn't come ig.

**Comment by Unlucky-Life** [comment]
@CaptainDead 
Hm this might have two reasons: 
Reason 1: of your wild pokemon moves are not properly found
Reason 2: you are missing certain sprites
- go to this link: 
- https://github.com/Unlucky-Life/ankimon/tree/04fb237261b89027e96c19f37799c3b48537fdab/missing_back_sprites
- copy these images into your "back_default" folder

**Comment by Unlucky-Life** [comment]
@CaptainDead The next update should come out this weekend or next

**Comment by CaptainDead** [comment]
I pasted those images, but it didn't fix the error but its not really a problem as it only happens if I answer cards real fast, and ig this might get solved with the new update maybe

**Comment by Unlucky-Life** [comment]
hm does it happen with all your main pokemon or just some ?

**Comment by CaptainDead** [comment]
Perfect... I didn't thought that could be a main specific problem, I changed my main and couldn't recreate it but when I went back to the one I had before, I got the error again.

This is the pokemon that's giving me the error when I have it selected as main - 
![image](https://github.com/Unlucky-Life/ankimon/assets/139457914/9fe0787d-2b9e-40b3-9ccc-4f19bc2edeae)

**Comment by Unlucky-Life** [comment]
yes it will ;)
and a cool little feature

**Comment by Unlucky-Life** [comment]
Uploading Benutzer 1 - Anki 2024-04-18 17-20-32.mp4…

**Comment by CaptainDead** [comment]
Love that, a real nice addition❤️‍🔥

**Comment by CaptainDead** [comment]
btw do we get XP everytime we defeat a pokemon or sometimes we don't get it? like I smtimes don't get any xp.

Also a lil issue - we get this in the center of screen when we catch a pokemon- 
![Screenshot 2024-04-19 004528](https://github.com/Unlucky-Life/ankimon/assets/139457914/9cba8ac3-2625-46d3-b47c-7694cfab0695)

The BG is dark and text is dark too, so its somewhat hard to read. just letting u know.

**Comment by CaptainDead** [comment]
Also in Charmander, one attack is repeated, so idk its a mistake or on purpose so just letting u know - 
![image](https://github.com/Unlucky-Life/ankimon/assets/139457914/7fa0a778-90a3-44ea-b39c-b62fdccbd59c)

**Comment by Unlucky-Life** [comment]
@CaptainDead so you have 2 times the same attack for your charmander is fine (not intended but doesnt hurt, maybe you let it relearn scratch)

- The tooltip color i may need to checkout - but i think i know why, could be an easy fix

- about the xp - yes everytime you defeat a pokemon you should receive xp - but the xp bar doesnt update real time yet
=> do you not always receive xp on defeat ? (hopefully its not the same issue as before)

**Comment by CaptainDead** [comment]
not talking about the xp bar, I just don't get any XP smtimes, and I get no error just no xp and the rest is normal,  

idk why... and I dont know what could be the reasons and its such a bother to try and fix it ig so I don't bother u over it cuz we already worked on it and rn I don't really have time to talk about this issue, so maybe the next update will fix it automatically (such a non-coder mineset😭, like how we think hitting a remote etc at the back will fix it if its not working) 

Anyway just wanted to know if we get xp each time, its fine we can work this issue out later when I have the time and the issue persists.

**Comment by Unlucky-Life** [comment]
@CaptainDead Oh man, sorry to hear that. Sadly the new anki version is as response 2.1.26 was quite responsive for errors - now finding the issue for an error is quite a guessing game....

But maybe it could also be you card_per_round setting - can you try to set it to 2 and see what happens ?

**Comment by face515** [comment]
This also happens to me. I think I know the problem. This only happens with my Terrakion. I believe it happens whenever the Bide move is randomly selected. As taking damage is not implemented yet, and Bide makes you wait, it doesn't know what to do. It most likely isn't implemented to wait, and since the opponent will always do 0 damage, multiplying by 0 could throw some error. Every other move works fine. It most likely happens with any move that multiplies the enemy's damage to you.
![image](https://github.com/Unlucky-Life/ankimon/assets/141896602/eb44a643-518a-403d-ad11-9afce8d075f7)

**Comment by face515** [comment]
Another thing to note is sometimes for me it would choose another move; other times it doesn't. It only chooses another when I am opening the deck(as it chooses an attack everytime that happens)

**Comment by face515** [comment]
Can OP send attack details of the problematic pokemon?

**Comment by Unlucky-Life** [comment]
@face515 Thanks for the information ! Yes its seems like there is a move where the code is trying to fetch a number for a certain value of the move such as (power for example) and then tries to do some kind of calculation with that number => but if there is no number to this key value then it throws an error. Therefore - Might need the code to just always retry to pick a diffrent attack. => Ill try to find out what the specific issue is the coming weeks. But thanks alot for the detailed info ! This does help alot !

**Comment by CaptainDead** [comment]
ohh I too have a bide attack in the pokemon that was giving me that error - 
![image](https://github.com/Unlucky-Life/ankimon/assets/139457914/09dfec38-2ed3-4130-81b6-c9136742db8e)
![image](https://github.com/Unlucky-Life/ankimon/assets/139457914/736c9ecf-2ccb-43bc-ae9b-fee6b62d932a)

**Comment by face515** [comment]
@Unlucky-Life no problem! just happy my pattern recognition can be used for something useful

**Comment by CaptainDead** [comment]
> But maybe it could also be you card_per_round setting - can you try to set it to 2 and see what happens ?

I tried it but didn't work.

I am not sure this is the thing but I feel like I always get XP after defeating a pokemon if I do my cards fast, could that be a thing? cuz when I am normally doing my cards, I sometimes don't get any XP, but when I quickly do cards in my 'experiment' deck, I always get the XP.

Also I always get XP whenever I try to record and show u that I dont XP, cuz at that time also I do the cards quickly.

Some of my decks take >10mins per card so ig that's a lot of time.

**Comment by Unlucky-Life** [comment]
Hm but i cant see a reason why the time of a card could play into this

**Comment by Unlucky-Life** [comment]
@CaptainDead do you have any video where i could see when you dont receive xp ?

**Comment by Unlucky-Life** [comment]
@CaptainDead another user said he doesnt gain xp when defeating the pokemon with the ankimon window open. Maybe that is the cause ?

**Comment by Unlucky-Life** [comment]
@CaptainDead I think i was able to recreate the bug ! If you defeat a pokemon and open the ankimon window => then defeat the pokemon (defeat screen appears on the ankimon window => then close the ankimon window => then do more cards => new pokemon is generated and no xp is gained (Not even the message appeared)
Was that the issue you had ?

![WhatsApp Bild 2024-04-30 um 20 50 54_9415a85a](https://github.com/Unlucky-Life/ankimon/assets/77027147/86e0424b-6e94-46e5-9765-6af4d139d15d)

**Comment by Unlucky-Life** [comment]
should have been fixes with the latest prereleases and refactoring of the cod
